import assert from 'node:assert/strict';

export async function verifyUX(browser, url) {
  let page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  const config = () => page.evaluate(async () => (await (await fetch('/api/ai/config')).json()));
  await page.goto(url, { waitUntil: 'networkidle' });
  await page.route('**/api/ai/config', route => route.request().method() === 'GET' ? route.fulfill({ status: 503, json: { error: 'load failed' } }) : route.continue());
  await page.locator('#settings-button').click();
  await page.getByRole('button', { name: '重新加载模型配置' }).waitFor();
  assert(await page.locator('#save-ai-config').isDisabled());
  await page.unroute('**/api/ai/config');
  await page.getByRole('button', { name: '重新加载模型配置' }).click();
  await page.locator('#ai-model').fill('current-form-model');
  await page.locator('#ai-base-url').fill(`${url}/mock`);
  await page.locator('#ai-key').fill('test-secret');
  await page.keyboard.press('Escape');
  const discard = page.getByRole('dialog', { name: '放弃未保存的修改？', exact: true });
  await discard.waitFor();
  await discard.getByRole('button', { name: '取消', exact: true }).click();
  assert.equal(await page.locator('#ai-key').inputValue(), 'test-secret');
  await page.locator('#ai-base-url').fill(`${url}/other`);
  assert.equal(await page.locator('#ai-key').inputValue(), '');
  await page.locator('#ai-key').fill('must-not-cross-protocol');
  await page.locator('#ai-provider').selectOption('anthropic');
  assert.equal(await page.locator('#ai-key').inputValue(), '');
  assert.equal(await page.locator('#ai-base-url').inputValue(), `${url}/other`);
  await page.locator('#ai-provider').selectOption('openai');
  await page.locator('#ai-base-url').fill(`${url}/mock`);
  await page.locator('#ai-key').fill('test-secret');
  let releaseTest;
  const testGate = new Promise(resolve => { releaseTest = resolve; });
  await page.route('**/api/ai/config/test', async route => { await testGate; await route.continue(); });
  await page.getByRole('button', { name: '保存并测试', exact: true }).click();
  await page.getByText('配置已保存，正在测试…', { exact: true }).waitFor();
  assert(await page.locator('#close-modal').isDisabled());
  await page.keyboard.press('Escape');
  assert.equal(await discard.count(), 0);
  releaseTest();
  await page.locator('#ai-settings-feedback').getByText('配置已保存，连接成功。', { exact: true }).waitFor();
  await page.unroute('**/api/ai/config/test');
  assert.equal((await config()).model, 'current-form-model'); // mock also checks model and Authorization.
  assert.equal(await page.locator('#ai-key').inputValue(), '');
  await page.locator('#ai-model').fill('test-will-fail');
  await page.route('**/api/ai/config/test', route => route.fulfill({ status: 503, json: { error: 'provider unavailable' } }));
  await page.getByRole('button', { name: '保存并测试', exact: true }).click();
  await page.locator('#ai-settings-feedback').getByText('保存成功，但连接测试失败：provider unavailable').waitFor();
  assert.equal((await config()).model, 'test-will-fail');
  await page.unroute('**/api/ai/config/test');
  await page.locator('#ai-model').fill('enter-saved-model');
  await page.locator('#ai-model').press('Enter');
  await page.getByText('已保存。密钥不会再次显示。', { exact: true }).waitFor();
  assert.equal((await config()).model, 'enter-saved-model');
  assert.equal(await page.locator('.top-title').textContent(), 'enter-saved-model');
  await page.getByRole('button', { name: '清除个人模型配置', exact: true }).click();
  let confirmation = page.getByRole('dialog', { name: '清除个人模型配置？', exact: true });
  await confirmation.getByRole('button', { name: '取消', exact: true }).click();
  await page.waitForFunction(() => document.activeElement?.textContent === '清除个人模型配置');
  assert((await config()).configured);
  await page.getByRole('button', { name: '清除个人模型配置', exact: true }).click();
  await confirmation.getByRole('button', { name: '确认清除', exact: true }).click();
  await page.locator('#ai-settings-feedback').getByText('个人配置已清除，已刷新当前生效状态。').waitFor();
  assert.equal((await config()).source, 'none');
  await page.locator('dialog').evaluate(e => e.scrollTop = 0);
  await page.screenshot({ path: 'test-results/ux-settings-desktop.png' });
  await page.locator('#ai-key').fill('discard-this');
  await page.locator('#close-modal').click();
  await discard.getByRole('button', { name: '放弃修改', exact: true }).click();
  await page.locator('#settings-button').click();
  await page.locator('#ai-key').waitFor();
  assert.equal(await page.locator('#ai-key').inputValue(), '');
  await page.locator('#close-modal').click();

  let creates = 0;
  page.on('request', req => { if (req.url().includes('/api/workspace/actions') && req.postDataJSON()?.type === 'create') creates++; });
  await page.locator('#create').dblclick();
  await page.locator('#draft').waitFor();
  await page.locator('#create').click();
  assert.equal(creates, 1);
  await page.waitForFunction(() => document.getElementById('draft') === document.activeElement);
  await page.locator('#manage-button').click();
  await page.locator('#topic-title').fill('First topic');
  await page.locator('#topic-title').press('Enter');
  await page.locator('#chat-header h1').getByText('First topic', { exact: true }).waitFor();
  await page.locator('#create').click();
  await page.locator('#chat-header h1').getByText('新的学习问题', { exact: true }).waitFor();
  await page.getByRole('button', { name: '更多：First topic', exact: true }).click();
  await page.locator('#topic-title').fill('Renamed other topic');
  await page.locator('#topic-tags').fill('math, math， algebra ');
  await page.locator('#topic-title').press('Enter');
  await page.getByRole('button', { name: '更多：Renamed other topic', exact: true }).waitFor();
  assert.equal(await page.locator('#chat-header h1').textContent(), '新的学习问题');
  await page.locator('#manage-button').click();
  await page.locator('[data-delete-session]').click();
  confirmation = page.getByRole('dialog', { name: '永久删除整个会话主线？', exact: true });
  assert(await confirmation.getByRole('button', { name: '永久删除会话', exact: true }).isDisabled());
  await confirmation.getByRole('button', { name: '取消', exact: true }).click();
  await page.locator('[data-delete-branch]').click();
  confirmation = page.getByRole('dialog', { name: '删除此主题？', exact: true });
  await confirmation.getByRole('button', { name: '取消', exact: true }).click();
  await page.locator('[data-delete-branch]').click();
  await page.route('**/api/workspace/actions?response=compact', async route => {
    if (route.request().postDataJSON().type === 'delete') { await new Promise(r => setTimeout(r, 200)); return route.fulfill({ status: 503, json: { error: 'delete failed' } }); }
    return route.continue();
  });
  await confirmation.getByRole('button', { name: '确认删除主题', exact: true }).click();
  await confirmation.getByRole('alert').getByText('delete failed').waitFor();
  await page.unroute('**/api/workspace/actions?response=compact');
  await confirmation.getByRole('button', { name: '确认删除主题', exact: true }).click();
  await page.locator('#undo').click();
  await page.locator('#chat-header h1').getByText('新的学习问题', { exact: true }).waitFor();
  await page.locator('#manage-button').click();
  await page.locator('[data-delete-branch]').click();
  await confirmation.getByRole('button', { name: '确认删除主题', exact: true }).click();
  await page.locator('#undo').waitFor();
  await page.locator('#draft').fill('mutation invalidates undo');
  await page.locator('#undo').waitFor({ state: 'hidden' });

  // Real pointer and keyboard selections, with viewport geometry assertions.
  await page.close();
  page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(url, { waitUntil: 'networkidle' });
  await page.locator('[data-sample]').click();
  const leaf = page.locator('.message.assistant [data-source-start]').filter({ hasText: '平方项总是非负' }).first();
  const selectWithPointer = async () => {
    await leaf.scrollIntoViewIfNeeded();
    const bounds = await leaf.evaluate(el => { const r = document.createRange(); r.selectNodeContents(el); const b = r.getClientRects()[0]; return { x: b.x, y: b.y, width: b.width, height: b.height }; });
    await page.mouse.move(bounds.x + 2, bounds.y + bounds.height / 2);
    await page.mouse.down();
    await page.mouse.move(bounds.x + Math.min(bounds.width - 2, 130), bounds.y + bounds.height / 2, { steps: 12 });
    await page.mouse.up();
    await page.locator('#expand-selection').waitFor();
  };
  const inBounds = async () => {
    const b = await page.getByRole('toolbar', { name: '选区操作' }).boundingBox();
    const v = page.viewportSize();
    assert(b.x >= 0 && b.y >= 0 && b.x + b.width <= v.width && b.y + b.height <= v.height);
  };
  await selectWithPointer();
  await inBounds();
  await page.screenshot({ path: 'test-results/ux-selection-desktop.png' });
  const before = await page.evaluate(() => window.getSelection().toString());
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write']);
  await page.getByRole('button', { name: '复制选中文字', exact: true }).click();
  await page.getByRole('status').getByText('已复制选中文字', { exact: true }).waitFor();
  assert.equal(await page.evaluate(() => navigator.clipboard.readText()), before);
  await page.evaluate(() => { window.originalClipboardWrite = navigator.clipboard.writeText; navigator.clipboard.writeText = async () => { throw new DOMException('denied', 'NotAllowedError'); }; });
  await page.getByRole('button', { name: '复制选中文字', exact: true }).click();
  await page.getByText('复制失败，请使用系统复制菜单或 Ctrl / Cmd + C。', { exact: true }).waitFor();
  await page.evaluate(() => { navigator.clipboard.writeText = window.originalClipboardWrite; });
  await page.locator('#expand-selection').click();
  await page.waitForFunction(() => document.getElementById('fork-prompt') === document.activeElement);
  await page.keyboard.press('Escape');
  await page.waitForFunction(text => window.getSelection()?.toString() === text, before);
  await page.keyboard.press('ArrowLeft');
  await page.keyboard.press('Shift+ArrowRight');
  await page.keyboard.press('Shift+ArrowRight');
  await page.locator('#expand-selection').waitFor();
  await inBounds();
  await page.keyboard.press('Escape');
  await page.locator('#expand-selection').waitFor({ state: 'hidden' });
  await selectWithPointer();
  await page.setViewportSize({ width: 1440, height: 500 });
  await page.locator('.chat').hover();
  await page.mouse.wheel(0, -1800);
  await page.locator('#expand-selection').waitFor({ state: 'hidden' });

  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('#nav-toggle').click();
  await page.locator('#create').click();
  await page.locator('#draft').waitFor();
  await page.waitForFunction(() => document.querySelector('#nav-toggle').getAttribute('aria-expanded') === 'false');
  await page.waitForFunction(() => document.getElementById('draft') === document.activeElement);
  await page.locator('#nav-toggle').click();
  await page.locator('#settings-button').click();
  await page.locator('#ai-model').waitFor();
  await page.screenshot({ path: 'test-results/ux-settings-mobile.png' });
  assert(await page.locator('dialog').evaluate(e => e.scrollWidth <= e.clientWidth));
  await page.locator('#close-modal').click();
  await page.locator('#nav-toggle').click();
  await page.locator('[data-switch]').filter({ hasText: '二次函数：从配方看见顶点' }).click();
  await selectWithPointer();
  await inBounds();
  await page.locator('.selection-feedback').waitFor({ state: 'hidden' });
  await page.screenshot({ path: 'test-results/ux-selection-mobile.png' });
  await page.keyboard.press('Escape');
  const formulaMessage = page.locator('.message.assistant').filter({ hasText: '平方项总是非负' }).first();
  await formulaMessage.getByRole('button', { name: '选择原文', exact: true }).click();
  const formula = await formulaMessage.locator('.message-text').evaluate(el => {
    const node = el.querySelector('[data-source-start]').firstChild;
    const start = node.textContent.indexOf('$'), end = node.textContent.indexOf('$', start + 1) + 1;
    if (start < 0 || end <= start) throw Error('Sample formula missing');
    const range = document.createRange(); range.setStart(node, start); range.setEnd(node, end);
    const selection = window.getSelection(); selection.removeAllRanges(); selection.addRange(range);
    return node.textContent.slice(start, end);
  });
  await page.locator('#expand-selection').click();
  assert.equal(await page.locator('#modal .full-text').first().textContent(), formula);
  await page.keyboard.press('Escape');
  assert.deepEqual(errors, []);
  await page.close();
  // The initial shell request must not overwrite a newer settings response.
  page = await browser.newPage();
  let first = true, releaseInitial;
  const initialGate = new Promise(resolve => { releaseInitial = resolve; });
  await page.route('**/api/ai/config', async route => {
    if (route.request().method() === 'GET' && first) {
      first = false;
      assert.match(await route.request().headerValue('cookie') ?? '', /zhishu_session=/, 'Model status must wait for the initial session cookie');
      const response = await route.fetch();
      await initialGate;
      return route.fulfill({ response });
    }
    return route.continue();
  });
  await page.goto(url, { waitUntil: 'domcontentloaded' });
  await page.locator('#settings-button').click();
  await page.locator('#ai-model').fill('newer-than-initial');
  await page.locator('#ai-base-url').fill(`${url}/mock`);
  await page.locator('#ai-key').fill('isolated-stale-response-test');
  await page.locator('#save-ai-config').click();
  await page.getByText('已保存。密钥不会再次显示。', { exact: true }).waitFor();
  await page.locator('#close-modal').click();
  releaseInitial();
  await page.waitForLoadState('networkidle');
  assert.equal(await page.locator('.top-title').textContent(), 'newer-than-initial');
  await page.close();
  console.log('UX: config retry/save-and-test/clear/discard; create dedupe/focus; non-active rename; delete failure/undo invalidation; pointer+keyboard selection; desktop/mobile geometry passed.');
}
