import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import ts from 'typescript';

const source = await readFile('apps/web/src/graph/gestures.ts', 'utf8');
const js = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext } }).outputText;
const { begin, advance, screen, world, zoomAt, segmentEntry } = await import(`data:text/javascript;base64,${Buffer.from(js).toString('base64')}`);
const camera = { x: 123, y: -37, scale: .62 }, point = { x: -223, y: 820 };
const roundtrip = world(screen(point, camera), camera);
assert(Math.abs(roundtrip.x - point.x) < 1e-9 && Math.abs(roundtrip.y - point.y) < 1e-9);
const cursor = { x: 300, y: 200 }, zoom = zoomAt(camera, cursor, 1.2);
assert.deepEqual(world(cursor, zoom), world(cursor, camera));
const boxes = [{ id: 'a', left: 100, top: 100, right: 144, bottom: 144 }, { id: 'b', left: 180, top: 100, right: 224, bottom: 144 }];
const start = begin(1, 0, { x: 0, y: 0 }, 0, boxes, camera);
assert.equal(advance(start, { x: 0, y: 0 }, 349).phase, 'pressCandidate');
assert.equal(advance(start, { x: 6, y: 0 }, 350).phase, 'lasso');
assert.equal(advance(start, { x: 8, y: 0 }, 20).phase, 'pan');
let jitter = advance(start, { x: 7, y: 0 }, 20);
assert.equal(advance(jitter, { x: 0, y: 0 }, 400).phase, 'pressCandidate');
const right = begin(2, 2, { x: 0, y: 122 }, 0, boxes, camera);
assert.equal(advance(right, { x: 23, y: 122 }, 20).phase, 'pressCandidate');
const stroke = advance(right, { x: 260, y: 122 }, 20);
assert.equal(stroke.phase, 'erasePreview'); assert.equal(stroke.target, 'a');
assert.equal(advance(stroke, { x: 200, y: 122 }, 30).target, 'a');
assert.equal(advance({ ...right, boxes: [boxes[0], { ...boxes[0], id: 'overlap' }] }, { x: 260, y: 122 }, 20).ambiguous, true);
assert.equal(advance(right, { x: 260, y: 122 }, 20, true).target, undefined);
assert.equal(segmentEntry({ x: 0, y: 0 }, { x: 50, y: 50 }, boxes[0]), undefined);
let bounded = right; for (let i = 0; i < 1000; i++) bounded = advance(bounded, { x: i, y: 122 }, i);
assert(bounded.path.length <= 128);
console.log('Gesture geometry: roundtrip, cursor zoom, hold/jitter/pan, fast first-hit, ambiguity, occlusion, bounded path passed.');
await import('./graph_geometry.mjs');
